name: ssh_example
description: Demonstrates how to use the ssh plugin.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0"

dependencies:
  cupertino_icons: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.1
  ssh:
    path: ../



flutter:
  uses-material-design: true
